### ISSUE TITLE
Cdavison

### ISSUE THREAD

**Issue by Gossaman** [Cdavison-development/SWINGANALYSR#1] opened 2024-02-18 15:06 UTC
[preprocess_videos.py](https://github.com/wmcnally/golfdb/blob/master/data/preprocess_videos.py) run error bbox[0]

**Comment by Cdavison-development** [comment] 2024-02-18 17:03
This is an error with the GolfDB system So im unsure of the cause or solution, on top of this i did not need to use the preprocess_videos.py script as the given 160x160 videos were suitable for my purposes

**Comment by Gossaman** [comment] 2024-03-01 15:23
Can you make a video of each step for me to watch?
I'm working on a project about this right now.

**Comment by Cdavison-development** [comment] 2024-03-10 13:10
a video of what? As i said, i didnt really make use of preprocess_videos.py in my project, like i said that script is only for changing the input configurations for videos

**Comment by Gossaman** [comment] 2024-03-13 08:33
Pose_estimation Which one must I use?

**Comment by Cdavison-development** [comment] 2024-03-13 14:10
Im not sure what your asking me, Ill try to get my full system to a clone and runable state within the next few weeks. 

If you want to see how the system works, look at the methodology section in the linked research paper

Also, feel free to ask more questions but please make them more readable, I cant help you if I dont know what your asking.

**Comment by Gossaman** [comment] 2024-03-14 14:46
What program do you use to run it?

**Comment by Cdavison-development** [comment] 2024-03-14 14:48
The README explains how to use the pose estimation system

**Comment by Cdavison-development** [comment] 2024-03-14 14:49
Can i ask, what are you planning to use my system for?

**Comment by Cdavison-development** [comment] 2024-03-14 21:18
I have just completely updated and fixed everything and the system should now work from clone

**Comment by Cdavison-development** [comment] 2024-03-21 13:56
if there are no more problems I will close this question

**Closed as completed** 2024-03-24 11:53 UTC
